server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb  # 메모리 모드 (기본)
    # url: jdbc:h2:file:./data/testdb  # 파일 모드 (선택 사항)
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    open-in-view: false

  h2:
    console:
      enabled: true  # H2 콘솔 활성화
      path: /h2-console  # 접속 경로 설정