services:
  account:
    build:
      context: ./
      dockerfile: account/Dockerfile
    container_name: dolleebank-account
    ports:
      - "8080:8080"
    working_dir: /app
    command: [ "./gradlew", "bootRun" ]
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dollee_bank
      SPRING_DATASOURCE_USERNAME: dollee_user
      SPRING_DATASOURCE_PASSWORD: dollee_pass
      SPRING_REDIS_HOST: redis
    networks:
      - backend
  deposit:
    build:
      context: ./
      dockerfile: deposit/Dockerfile
    container_name: dolleebank-deposit
    ports:
      - "8082:8082"
    working_dir: /app
    command: [ "./gradlew", "bootRun" ]
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dollee_bank
      SPRING_DATASOURCE_USERNAME: dollee_user
      SPRING_DATASOURCE_PASSWORD: dollee_pass
      SPRING_REDIS_HOST: redis
    networks:
      - backend
  withdraw:
    build:
      context: ./
      dockerfile: withdraw/Dockerfile
    container_name: dolleebank-withdraw
    ports:
      - "8084:8084"
    working_dir: /app
    command: [ "./gradlew", "bootRun" ]
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dollee_bank
      SPRING_DATASOURCE_USERNAME: dollee_user
      SPRING_DATASOURCE_PASSWORD: dollee_pass
      SPRING_REDIS_HOST: redis
    networks:
      - backend
  transfer:
    build:
      context: ./
      dockerfile: transfer/Dockerfile
    container_name: dolleebank-transfer
    ports:
      - "8086:8086"
    working_dir: /app
    command: [ "./gradlew", "bootRun" ]
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dollee_bank
      SPRING_DATASOURCE_USERNAME: dollee_user
      SPRING_DATASOURCE_PASSWORD: dollee_pass
      SPRING_REDIS_HOST: redis
    networks:
      - backend
networks:
  backend:

