services:
  mysql:
    image: mysql:8.3
    container_name: dev-mysql
    environment:
      MYSQL_DATABASE: dollee_bank
      MYSQL_USER: dollee_user
      MYSQL_PASSWORD: dollee_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  redis:
    image: redis:7.2
    container_name: dev-redis
    ports:
      - "6379:6379"
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
