services:
  app:
    build:
      context: ../account
    container_name: dolleebank-account
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dollee_bank
      SPRING_DATASOURCE_USERNAME: dollee_user
      SPRING_DATASOURCE_PASSWORD: dollee_pass
      SPRING_REDIS_HOST: redis
    networks:
      - backend
networks:
  backend:

