server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dollee_bank?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: dollee_user
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create  # 또는 validate, none, create 등
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  redis:
    host: localhost
    port: 6379
